server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///security_oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: server


mybatis:
  type-aliases-package: cn.lx.security.domain
  configuration:
    #驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    cn.lx.security: debug

encrypt:
  key-store:
    alias: testoauth
    location: classpath:/testoauth.jks
    password: testoauth
    secret: testoauth

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
