server:
  port: 8091

logging:
  level:
    cn.lx.security: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: resource2
